# -*- coding: utf-8 -*-
"""prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQG0KvUCWcxJNlEy1d5tpQXvnL26O8pw
"""

n=int(input("Enter number:"))
i=1;c=0
while i<=n:
  j=1;f=0
  if(n%i==0):
    while j<=i:
      if(i%j==0):
        f=f+1
      j=j+1
  if(f==2):
    c=c+1
  i=i+1
print(c)